image: maven:3.8.1-openjdk-17

stages:
  - build
  - test

build-job:
  stage: build
  script: "mvn clean -f ./backend/pom.xml"

test-job:
  stage: test
  script: "mvn install -B -f ./backend/pom.xml"
