export enum WerewolfVoiceLineType {
  START = "START",
  END = "END",
  DEATH = "DEATH",
  PLAYER_SLEEP = "PLAYER_SLEEP",
  VILLAGE_WAKE = "VILLAGE_WAKE",
  VILLAGE_SLEEP = "VILLAGE_SLEEP",
  WEREWOLVES_WAKE = "WEREWOLVES_WAKE",
  WEREWOLVES_SLEEP = "WEREWOLVES_SLEEP",
  SEER_WAKE = "SEER_WAKE",
  VILLAGERS_VOTE = "VILLAGERS_VOTE"
}
