export enum WerewolfVoteDescriptor {
  VILLAGERS_LYNCH = "VILLAGERS_LYNCH",
  WEREWOLVES_KILL = "WEREWOLVES_KILL",
  SEER_SEE = "SEER_SEE",
  WITCH_HEAL = "WITCH_HEAL",
  WITCH_KILL = "WITCH_KILL",
  HUNTER_SHOOT = "HUNTER_SHOOT",
}
