export enum WerewolfLogType {
  START = "START",
  END = "END",
  SLEEP = "SLEEP",
  WAKE = "WAKE",
  DEATH = "DEATH",
  WEREWOLVES_VOTE = "WEREWOLVES_VOTE",
  SEER_SUCCESS = "SEER_SUCCESS",
  SEER_FAILURE = "SEER_FAILURE",
  VILLAGERS_VOTE = "VILLAGERS_VOTE"
}
