export enum VoteType {
  PUBLIC_PUBLIC_PUBLIC = 'PUBLIC_PUBLIC_PUBLIC',
  PUBLIC_PUBLIC_REVEAL = 'PUBLIC_PUBLIC_REVEAL',
  PUBLIC_PUBLIC_PRIVATE = 'PUBLIC_PUBLIC_PRIVATE',
  PRIVATE_PUBLIC_PUBLIC = 'PRIVATE_PUBLIC_PUBLIC'
}
